# Generated by Django 3.1.5 on 2021-01-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_libro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'fecha'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
