# Generated by Django 3.1.5 on 2021-01-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20210115_1207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='libro',
            table='Libro',
        ),
    ]
